[tool.poetry]
name = "pillbugplants"
version = "0.1.0"
description = ""
authors = ["autoaicodingtest <autoaicodingtest>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aider-install = "^0.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
