feat(physics): add new physics logic module for pillbugplants game simulation development 
feat(entities): introduce entity struct definitions and behaviors required by the entities of our project.  
... etc ...
